name: testimony_transcriber
description: Flutter desktop transcription app for court audio.
publish_to: "none"
version: 2.1.11+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  dio: ^5.4.3
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.4
  web_socket_channel: ^2.4.0
  just_audio: ^0.9.38
  just_audio_windows: ^0.2.1
  flutter_quill: ^11.5.0
  path_provider: ^2.1.3
  logging: ^1.2.0
  file_selector: ^1.0.3
  html: ^0.15.4
  google_fonts: ^6.1.0
  package_info_plus: ^8.0.0
  http: ^1.1.0
  ffi: ^2.1.0
  win32: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  ffigen: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/images/testimony.png
