name: testimony_transcriber
description: Flutter desktop transcription app for court audio.
publish_to: "none"
version: 2.1.7+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  dio: ^5.4.3
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.4
  web_socket_channel: ^2.4.0
  just_audio: ^0.9.38
  just_audio_windows: ^0.2.1
  path_provider: ^2.1.3
  window_manager: ^0.4.3
  flutter_quill: ^11.5.0
  vsc_quill_delta_to_html: ^1.0.5
  dart_quill_delta: ^10.8.3

dependency_overrides:
  intl: ^0.19.0
  logging: ^1.2.0
  file_selector: ^1.0.3
  html: ^0.15.4
  google_fonts: ^6.1.0
  package_info_plus: ^8.0.0
  http: ^1.1.0
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_audio: ^1.0.7
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/images/testimony.png
    - assets/images/jsc_logo_1.webp
    - assets/images/logo.png

msix_config:
  display_name: Testimony Transcriber
  publisher_display_name: Testimony
  identity_name: com.testimony.transcriber
  msix_version: 2.1.7.0
  logo_path: assets/images/logo.png
  capabilities: internetClient
  install_certificate: false
